version: '3'
services:
  animals:
    build: 
      context: ./
      args:
        - VERSION
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
     - "8080:8080"
     - "9080:9080"
    links:
      - mongo
  mongo:
    image: mongo
