version: '3'
services:
  navigation:
    build: ./navigation
  recipes:
    build: ./recipes
  frontend:
    image: nginx
    ports:
     - "80:80"
    links:
    - navigation
    - recipes
    volumes:
    - ./frontend/src:/usr/share/nginx/html
    - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
