version: '3'
services:
  navigation:
    build: ./navigation
    links:
    - redis
  main:
    build: ./main
    environment:
      APPLICATION_URL: "http://localhost"
  recipes:
    build: ./recipes
    links:
    - redis
  cookbooks:
    build: ./cookbooks
    links:
    - redis
  frontend:
    image: nginx
    ports:
     - "80:80"
    links:
    - navigation
    - recipes
    volumes:
    - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis
    ports: 
    - "6379:6379"
    