management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level: 
    net.caimito: DEBUG
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaewv61fi0xPP6tG0h7
            client-secret: K9OLC5n2wePsPk7bf9eZPC5Cb-N0vI2XnmkJyiET
        provider:
          okta:
            authorization-uri: https://dev-148541.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-148541.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-148541.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-148541.oktapreview.com/oauth2/default/v1/keys
