# config/cucumber.yml
##YAML Template
---
default: --tags 'not @todo'
html_report: --format progress --format html --out=target/features.html
json_report: --format progress --format json --out=target/features.json
